"""
ParkWatch Dashboard
====================
Streamlit app visualizing parking violation hotspots and their
estimated Congestion Impact Score across Bengaluru.

Run with: streamlit run app.py
"""

import streamlit as st
import pandas as pd
import numpy as np
import pydeck as pdk
import plotly.express as px
import ast
import os
import requests

st.set_page_config(page_title="ParkWatch — Congestion Intelligence", layout="wide")

# ──────────────────────────────────────────────────────────────────────────
# Load data
# ──────────────────────────────────────────────────────────────────────────
# Data is hosted on Hugging Face Datasets (public) since the raw/cleaned CSVs
# are too large to commit to the GitHub repo (109MB and 128MB respectively,
# over GitHub's comfortable limits). On Streamlit Community Cloud, these are
# downloaded once on app startup and cached. For local development, if the
# files already exist in the working directory (e.g. freshly generated by
# running pipeline.py), those are used directly instead of re-downloading.
#
# IMPORTANT: replace YOUR_USERNAME below with your actual Hugging Face
# username once the dataset is uploaded.
HF_BASE_URL = "https://huggingface.co/datasets/baibhavbaidya/parkwatch-data/resolve/main"
GEO_SCORES_URL = f"{HF_BASE_URL}/geo_cell_scores.csv" 
VIOLATIONS_URL = f"{HF_BASE_URL}/cleaned_violations.csv" 

LOCAL_GEO_SCORES = "geo_cell_scores.csv"
LOCAL_VIOLATIONS = "cleaned_violations.csv"


def download_if_needed(url, local_path):
    """Download a file from a URL to a local cache path if not already present."""
    if os.path.exists(local_path):
        return local_path
    cache_path = f"/tmp/{os.path.basename(local_path)}" if not os.access(".", os.W_OK) else local_path
    if os.path.exists(cache_path):
        return cache_path
    response = requests.get(url, stream=True, timeout=120)
    response.raise_for_status()
    with open(cache_path, "wb") as f:
        for chunk in response.iter_content(chunk_size=8192):
            f.write(chunk)
    return cache_path


@st.cache_data(show_spinner="Loading violation data (first load may take a moment)...")
def load_data():
    # Prefer local files (fast path for local dev after running pipeline.py)
    if os.path.exists(LOCAL_GEO_SCORES) and os.path.exists(LOCAL_VIOLATIONS):
        geo_path = LOCAL_GEO_SCORES
        viol_path = LOCAL_VIOLATIONS
    else:
        geo_path = download_if_needed(GEO_SCORES_URL, LOCAL_GEO_SCORES)
        viol_path = download_if_needed(VIOLATIONS_URL, LOCAL_VIOLATIONS)

    agg = pd.read_csv(geo_path)
    violations = pd.read_csv(viol_path)
    violations['violations_list'] = violations['violations_list'].apply(
        lambda x: ast.literal_eval(x) if isinstance(x, str) else []
    )
    return agg, violations

agg, violations = load_data()

# Hotspots = cells with enough volume to be statistically meaningful
hotspots = agg[agg['violation_count'] >= 20].copy()
hotspots = hotspots.sort_values('congestion_impact_score', ascending=False).reset_index(drop=True)

# ──────────────────────────────────────────────────────────────────────────
# Header & summary stats
# ──────────────────────────────────────────────────────────────────────────
st.title("🚦 ParkWatch — Parking-Induced Congestion Intelligence")
st.caption(
    "AI-driven hotspot detection and estimated congestion impact scoring, "
    "built from Bengaluru Traffic Police parking violation records "
    "(Nov 2023 – Apr 2024)."
)

col1, col2, col3, col4 = st.columns(4)
col1.metric("Total Violations Analyzed", f"{len(violations):,}")
col2.metric("Hotspot Locations Identified", f"{len(hotspots):,}")
col3.metric("Avg. Estimated Capacity Loss", f"{hotspots['avg_capacity_loss'].mean()*100:.0f}%")
col4.metric("Police Stations Covered", f"{agg['police_station'].nunique()}")

st.divider()

# ──────────────────────────────────────────────────────────────────────────
# Map
# ──────────────────────────────────────────────────────────────────────────
st.subheader("📍 Hotspot Map — Congestion Impact Score")
st.caption(
    "Each point is a location cluster of parking violations. "
    "Color and size scale with the Estimated Congestion Impact Score "
    "(red = highest priority for enforcement)."
)

map_data = hotspots.copy()

# Color scale: green (low) -> yellow -> red (high), based on score percentile
def score_to_color(score, min_s, max_s):
    pct = (score - min_s) / (max_s - min_s + 1e-9)
    r = int(255 * pct)
    g = int(255 * (1 - pct))
    return [r, g, 40, 180]

min_s, max_s = map_data['congestion_impact_score'].min(), map_data['congestion_impact_score'].max()
map_data['color'] = map_data['congestion_impact_score'].apply(lambda s: score_to_color(s, min_s, max_s))
map_data['radius'] = 30 + (map_data['congestion_impact_score'] / max_s) * 200

layer = pdk.Layer(
    "ScatterplotLayer",
    data=map_data,
    get_position=['lon', 'lat'],
    get_fill_color='color',
    get_radius='radius',
    pickable=True,
    opacity=0.7,
)

view_state = pdk.ViewState(
    latitude=map_data['lat'].mean(),
    longitude=map_data['lon'].mean(),
    zoom=10.5,
    pitch=0,
)

tooltip = {
    "html": "<b>{display_name}</b><br/>"
            "Police Station: {police_station}<br/>"
            "Violations: {violation_count}<br/>"
            "Est. Capacity Loss: {avg_capacity_loss}<br/>"
            "Peak Hour: {peak_hour}:00<br/>"
            "Impact Score: {congestion_impact_score}",
    "style": {"backgroundColor": "steelblue", "color": "white"},
}

st.pydeck_chart(pdk.Deck(
    layers=[layer],
    initial_view_state=view_state,
    tooltip=tooltip,
    map_provider="carto",
    map_style="dark",
))

st.divider()

# ──────────────────────────────────────────────────────────────────────────
# Top hotspots table + drill-down
# ──────────────────────────────────────────────────────────────────────────
left, right = st.columns([1, 1])

with left:
    st.subheader("🏆 Top Priority Enforcement Zones")
    top_n = st.slider("Show top N hotspots", 5, 50, 15)
    display_table = hotspots.head(top_n)[[
        'display_name', 'police_station', 'violation_count',
        'avg_capacity_loss', 'peak_hour', 'congestion_impact_score'
    ]].copy()
    display_table.columns = ['Location', 'Police Station', 'Violations',
                              'Est. Capacity Loss', 'Peak Hour', 'Impact Score']
    display_table['Est. Capacity Loss'] = (display_table['Est. Capacity Loss'] * 100).round(0).astype(int).astype(str) + '%'
    display_table['Peak Hour'] = display_table['Peak Hour'].astype(int).astype(str) + ':00'
    display_table['Impact Score'] = display_table['Impact Score'].round(1)
    st.dataframe(display_table, use_container_width=True, hide_index=True)

with right:
    st.subheader("🕒 Select a Hotspot to See Time Pattern")
    selected_location = st.selectbox(
        "Choose a location",
        hotspots.head(top_n)['display_name'].tolist()
    )
    sel_row = hotspots[hotspots['display_name'] == selected_location].iloc[0]
    sel_cell = sel_row['geo_cell']

    cell_violations = violations[violations['geo_cell'] == sel_cell]

    hourly = cell_violations.groupby('hour').size().reindex(range(24), fill_value=0).reset_index()
    hourly.columns = ['Hour', 'Violations']

    fig = px.bar(
        hourly, x='Hour', y='Violations',
        title=f"Hourly Violation Pattern — {selected_location}",
        color='Violations', color_continuous_scale='OrRd'
    )
    fig.update_layout(showlegend=False, height=350, dragmode=False)
    st.plotly_chart(fig, use_container_width=True, config={'displayModeBar': False})

st.divider()

# ──────────────────────────────────────────────────────────────────────────
# Composition breakdown for selected hotspot
# ──────────────────────────────────────────────────────────────────────────
st.subheader(f"🔍 Violation Composition — {selected_location}")

c1, c2 = st.columns(2)

with c1:
    all_viol_types = [v for lst in cell_violations['violations_list'] for v in lst]
    viol_counts = pd.Series(all_viol_types).value_counts().reset_index()
    viol_counts.columns = ['Violation Type', 'Count']
    fig2 = px.bar(
        viol_counts, x='Count', y='Violation Type', orientation='h',
        title="Violation Types at this Location"
    )
    fig2.update_layout(height=350, yaxis={'categoryorder': 'total ascending'}, dragmode=False)
    st.plotly_chart(fig2, use_container_width=True, config={'displayModeBar': False})

with c2:
    vehicle_counts = cell_violations['vehicle_type'].value_counts().head(8).reset_index()
    vehicle_counts.columns = ['Vehicle Type', 'Count']
    fig3 = px.pie(
        vehicle_counts, names='Vehicle Type', values='Count',
        title="Vehicle Types Involved"
    )
    fig3.update_layout(height=350)
    st.plotly_chart(fig3, use_container_width=True, config={'displayModeBar': False})

st.divider()

# ──────────────────────────────────────────────────────────────────────────
# Methodology note (for judges)
# ──────────────────────────────────────────────────────────────────────────
with st.expander("ℹ️ Methodology: How is the Congestion Impact Score calculated?"):
    st.markdown("""
    **This dataset contains parking violation records only — it does not contain
    direct traffic-flow sensor data (speed, travel time, vehicle counts).**
    The Congestion Impact Score is therefore an **estimate**, built from three
    independently validated components:

    1. **Violation Density** (50% weight) — the number of recorded violations
       at a location (log-scaled). This is the most statistically reliable
       signal: a location with hundreds of repeat violations over 6 months is
       very likely a real, recurring problem area.

    2. **Estimated Capacity Loss** (30% weight) — based on traffic-engineering
       principles (Highway Capacity Manual-style lane-blockage analysis), each
       violation type is assigned an estimated percentage of road capacity
       lost when that type of obstruction occurs (e.g. blocking a main road
       lane causes a larger capacity loss than a footpath violation).

    3. **Repeat-Vehicle Ratio** (20% weight) — the share of violations coming
       from vehicles caught more than once at the same location. This flags
       entrenched, ongoing problem spots (repeat offenders) rather than
       one-off incidents, and is a natural starting point for targeted
       enforcement.

    **Locations are geo-clustered using DBSCAN** (density-based spatial
    clustering) on latitude/longitude rather than simple grid rounding, so
    that one large junction's violations aren't artificially split into many
    separate "hotspots" just because they're spread across a wide area.

    Locations with fewer than 20 recorded violations are excluded from the
    priority hotspot list, since smaller samples produce statistically
    unreliable rankings (verified during model validation — each component
    above was checked to ensure it correlates meaningfully and independently
    with the final score, with no single factor dominating or duplicating
    another).

    **This is a prioritization tool, not a direct measurement of congestion.**
    For production deployment, we recommend calibrating this score against
    real traffic-flow data (e.g. from a live traffic API) where available.
    """)

st.caption("Built for Hackathon Round 2 — Theme: Poor Visibility on Parking-Induced Congestion")